def D_chooser(candidate: int) -> int: ...


def U_V_subscript(k: int, n: int, U: int, V: int, P: int, Q: int, D: int) -> int: ...


def LucasPseudoPrime(n: int, D: int, P: int, Q: int) -> int: ...


def jacobi(a: int, n: int) -> int: ...
