from _typeshed import Incomplete
from cryptography318.factor import ecm as ecm, qs as siqs
from cryptography318.prime.prime import isprime as isprime, next_prime as next_prime, primesieve as primesieve

def factor(n, use_rho: bool = ..., use_ecm: bool = ..., use_pm1: bool = ..., use_siqs: bool = ..., limit: Incomplete | None = ..., verbose: bool = ..., *, details: Incomplete | None = ...): ...
def pollard_pm1(n, B: Incomplete | None = ..., retry: int = ...): ...
def pollard_rho_factor(n, mix: Incomplete | None = ..., retry: int = ...): ...
def factor_small(factors, n, limit): ...
